(()=>{
'use strict';
const $=id=>document.getElementById(id),KEY='savewise_v1',AV=['🙂','😎','🤓','😄','🥳','🤩','😇','🤑','😌','🧑','👨','👩','🧔','👨‍💻','👩‍💻','🧑‍🎨','🦸','🧙','🐼','🐯','🦊','🐸','🐨','🐵'],CUR={INR:'₹',USD:'$',EUR:'€',GBP:'£'};
let db;try{db=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{db={}}if(!Array.isArray(db.profiles)||!db.profiles.length)db.profiles=[{id:1,name:'You',currency:'INR',balance:0,budget:0,transactions:[],goals:[],avatar:'🙂'}];if(!db.active)db.active=db.profiles[0].id;if(!db.theme)db.theme='dark';
const p=()=>db.profiles.find(x=>x.id===db.active)||db.profiles[0],save=()=>localStorage.setItem(KEY,JSON.stringify(db)),money=n=>(CUR[p().currency]||'₹')+Number(n||0).toLocaleString(),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),toast=s=>{let t=$('toast');if(t){t.textContent=s;t.classList.add('show');clearTimeout(window.__swT);window.__swT=setTimeout(()=>t.classList.remove('show'),2200)}};
function theme(){let dark=db.theme==='dark'||(db.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.classList.toggle('dark',dark);document.body.classList.toggle('light',!dark);if($('themeBtn'))$('themeBtn').textContent=dark?'🌙':'☀️';if($('swThemeBtn'))$('swThemeBtn').textContent=dark?'Switch to Light':'Switch to Dark'}
function closeInsights(){let x=$('insightsModal');if(x)x.classList.remove('show');let a=$('aiPanel');if(a)a.classList.remove('show')}
function openPage(id){document.querySelectorAll('.sw-page-layer').forEach(x=>{x.classList.remove('show');x.setAttribute('aria-hidden','true')});closeInsights();let x=$(id);if(!x)return;x.classList.add('show');x.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';if(id==='settingsPage')clock();if(id==='goalsPage')goals();if(id==='profilePage')profile()}
function closePage(id){let x=$(id);if(x)x.classList.remove('show');document.body.style.overflow=''}
function clock(){let d=new Date(),tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'Local';if($('clockLabel'))$('clockLabel').textContent=d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});if($('dateLabel'))$('dateLabel').textContent=d.toLocaleDateString([],{weekday:'long',day:'numeric',month:'short',year:'numeric'});if($('tzLabel'))$('tzLabel').textContent='🕐 '+tz;if($('swSettingsTimezone'))$('swSettingsTimezone').textContent='Automatically detected • '+tz}
function home(){let q=p(),now=new Date(),tx=(q.transactions||[]).filter(t=>{let d=new Date(t.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}),inc=tx.filter(t=>t.type==='income').reduce((a,t)=>a+Number(t.amount||0),0),exp=tx.filter(t=>t.type==='expense').reduce((a,t)=>a+Number(t.amount||0),0);if($('balance'))$('balance').textContent=money(q.balance);if($('income'))$('income').textContent='+ '+money(inc);if($('expense'))$('expense').textContent='− '+money(exp);if($('monthLabel'))$('monthLabel').textContent=now.toLocaleDateString(undefined,{month:'long',year:'numeric'});if($('monthMeta'))$('monthMeta').textContent=`${tx.length} transaction${tx.length===1?'':'s'} in this month`;theme()}
function goals(){let h=$('swGoalsContent');if(!h)return;let gs=Array.isArray(p().goals)?p().goals:[];h.innerHTML=gs.length?'<div class="sw-page-grid">'+gs.map(g=>{let pct=g.target?Math.min(100,g.saved/g.target*100):0;return `<div class="sw-goal-card"><h3>${g.icon||'🎯'} ${esc(g.name)}</h3><p>${money(g.saved)} of ${money(g.target)} • ${Math.round(pct)}%</p><div class="goalbar"><i style="width:${pct}%"></i></div><p>Goal date: ${g.date?new Date(g.date+'T00:00:00').toLocaleDateString():'Not set'}</p></div>`}).join('')+'</div><button class="btn primary" id="swPageAddGoal" style="margin-top:14px">＋ Add goal</button>':'<div class="sw-setting-card" style="text-align:center;padding:35px"><div style="font-size:34px">🐷</div><h3>No savings goals yet</h3><p>Create a goal for a trip, emergency fund, gadget or anything important to you.</p><button class="btn primary" id="swEmptyAddGoal">Create your first goal</button></div>';let a=$('swEmptyAddGoal')||$('swPageAddGoal');if(a)a.onclick=goalCreate}
function goalCreate(){openPage('goalCreatePage');let d=$('swGoalDate');if(d&&!d.value){let x=new Date();x.setMonth(x.getMonth()+1);d.value=x.toISOString().slice(0,10)}requestAnimationFrame(()=>$('swGoalName')?.focus())}
function goalSave(){let n=$('swGoalName')?.value.trim(),t=+$('swGoalTarget')?.value,s=+$('swGoalSaved')?.value||0,d=$('swGoalDate')?.value,i=$('swGoalIcon')?.value||'🎯';if(!n||t<=0||!d)return toast('Complete the goal details.');if(s<0||s>t)return toast('Already saved must be between 0 and target.');p().goals=p().goals||[];p().goals.push({id:Date.now(),name:n,target:t,saved:s,date:d,icon:i});save();closePage('goalCreatePage');openPage('goalsPage');toast('Savings goal created ✓')}
function profile(){let q=p(),a=q.avatar||'🙂';if($('swProfileName'))$('swProfileName').value=q.name||'You';if($('swProfileEmail'))$('swProfileEmail').value=q.email||'';if($('swProfileAbout'))$('swProfileAbout').value=q.about||'';if($('swProfilePreviewName'))$('swProfilePreviewName').textContent=q.name||'You';if($('swAvatarPreview'))$('swAvatarPreview').textContent=a;if($('headerAvatar'))$('headerAvatar').textContent=a;let g=$('swAvatarGrid');if(!g)return;g.innerHTML=AV.map(x=>`<button type="button" class="sw-avatar-choice ${x===a?'active':''}" data-avatar="${x}">${x}</button>`).join('');g.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{q.avatar=b.dataset.avatar;save();profile()})}
function legal(t){openPage('legalPage');if($('legalTitle'))$('legalTitle').textContent=t==='privacy'?'Privacy Notice':'Terms & Conditions';if($('legalContent'))$('legalContent').innerHTML=t==='privacy'?'<h3>Local data</h3><p>Core budgeting records stay in local browser storage in this prototype.</p><h3>Permissions</h3><p>Local time comes from your device/browser clock. Precise location is not required.</p>':'<h3>Intended use</h3><p>SaveWise is a personal budgeting and expense-tracking tool.</p><h3>Accuracy</h3><p>Check your own amounts, dates and decisions. Prototype features may change.</p>'}
function aiInsights(){
 const q=p(),tx=Array.isArray(q.transactions)?q.transactions:[],now=new Date(),month=tx.filter(t=>{const d=new Date(t.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}),inc=month.filter(t=>t.type==='income').reduce((a,t)=>a+Number(t.amount||0),0),exp=month.filter(t=>t.type==='expense').reduce((a,t)=>a+Number(t.amount||0),0),net=inc-exp;
 const cats={};month.filter(t=>t.type==='expense').forEach(t=>{const c=t.category||'Other';cats[c]=(cats[c]||0)+Number(t.amount||0)});const top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];
 let advice=exp===0?'No expenses recorded this month yet. Add a few transactions and I can spot spending patterns.':net<0?'Your spending is above your recorded income this month. Review the largest category and trim one flexible expense first.':top?`${top[0]} is your largest expense category at ${money(top[1])}. Keep an eye on it before making non-essential purchases.`:'Your spending is currently spread across categories.';
 const pct=inc?Math.round(net/inc*100):0;
 const html=`<div class="sw-ai-sheet"><div class="sw-ai-kicker">SMART MONEY CHECK</div><h2>Your money snapshot</h2><p class="sw-ai-copy">${esc(advice)}</p><div class="sw-ai-stats"><div><span>Income</span><strong>${money(inc)}</strong></div><div><span>Spent</span><strong>${money(exp)}</strong></div><div><span>Net</span><strong>${money(net)}</strong></div><div><span>Saved rate</span><strong>${pct}%</strong></div></div><div class="sw-ai-tip"><b>Next best move</b><p>${net<0?'Pause one discretionary purchase and review your biggest expense.':exp===0?'Start logging expenses so SaveWise can give useful recommendations.':`Try to keep your next ${money(Math.max(0,net*.25))} of spending intentional.`}</p></div><button class="btn primary sw-ai-close">Done</button></div>`;
 let panel=$('aiPanel');if(!panel){panel=document.createElement('div');panel.id='aiPanel';panel.className='sw-ai-overlay';document.body.appendChild(panel)}panel.innerHTML=html;panel.classList.add('show');panel.onclick=e=>{if(e.target===panel||e.target.closest('.sw-ai-close'))panel.classList.remove('show')}
}
function bind(){
$('settingsNav')?.addEventListener('click',()=>openPage('settingsPage'));$('goalsNav')?.addEventListener('click',()=>openPage('goalsPage'));$('headerAvatar')?.addEventListener('click',()=>openPage('profilePage'));
$('homeNav')?.addEventListener('click',()=>{document.querySelectorAll('.sw-page-layer.show').forEach(x=>x.classList.remove('show'));closeInsights();document.body.style.overflow=''});
$('swThemeBtn')?.addEventListener('click',()=>{db.theme=db.theme==='dark'?'light':db.theme==='light'?'system':'dark';save();theme()});$('themeBtn')?.addEventListener('click',()=>{db.theme=db.theme==='dark'?'light':'dark';save();theme()});
$('swNotifyBtn')?.addEventListener('click',()=>openPage('notificationsPage'));$('swBackupBtn')?.addEventListener('click',()=>openPage('backupPage'));$('swProfileBtn')?.addEventListener('click',()=>openPage('profilePage'));
$('swExportBackup')?.addEventListener('click',()=>{let u=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='savewise-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)});$('swImportBackup')?.addEventListener('change',e=>{let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!Array.isArray(d.profiles))throw 0;db=d;save();location.reload()}catch{toast('Invalid SaveWise backup.')}};r.readAsText(f)});
$('swResetBtn')?.addEventListener('click',()=>{if(confirm('Reset SaveWise data on this device? This cannot be undone.')){localStorage.removeItem(KEY);localStorage.removeItem('savewise_terms_privacy_accepted_v1');location.reload()}});
document.querySelectorAll('[data-open-legal]').forEach(b=>b.onclick=()=>legal(b.dataset.openLegal));document.querySelectorAll('[data-close-page]').forEach(b=>b.onclick=()=>closePage(b.dataset.closePage));
$('swAddGoalBtn')?.addEventListener('click',goalCreate);$('swGoalCreateBack')?.addEventListener('click',()=>{closePage('goalCreatePage');openPage('goalsPage')});$('swGoalCancel')?.addEventListener('click',()=>{closePage('goalCreatePage');openPage('goalsPage')});$('swGoalSave')?.addEventListener('click',goalSave);$('addGoal')?.addEventListener('click',()=>openPage('goalsPage'));
$('swSaveProfile')?.addEventListener('click',()=>{let q=p();q.name=$('swProfileName')?.value.trim()||'You';q.email=$('swProfileEmail')?.value.trim()||'';q.about=$('swProfileAbout')?.value.trim()||'';save();profile();home();toast('Profile saved ✓')});
$('swRequestNotifications')?.addEventListener('click',async()=>{if(!('Notification'in window))return toast('Notifications are not supported here.');let r=await Notification.requestPermission();if($('swNotificationStatus'))$('swNotificationStatus').textContent='Status: '+r;if(r==='granted')new Notification('SaveWise',{body:'Smart money reminders are enabled.'})});$('swTestNotification')?.addEventListener('click',()=>{if('Notification'in window&&Notification.permission==='granted')new Notification('SaveWise test',{body:'Notification test'});try{navigator.vibrate?.([20,30,40])}catch{}});
$('swReadPrivacy')?.addEventListener('click',()=>legal('privacy'));$('swReadTerms')?.addEventListener('click',()=>legal('terms'));$('swConsentCheck')?.addEventListener('change',e=>{if($('swAccept'))$('swAccept').disabled=!e.target.checked});$('swAccept')?.addEventListener('click',()=>{if($('swConsentCheck')?.checked){localStorage.setItem('savewise_terms_privacy_accepted_v1','yes');$('firstRunConsent')?.classList.remove('show')}});
const s=document.createElement('style');s.textContent=`
:root{--bg:#07111f;--surface:#0d1b2a;--surface2:#12263a;--text:#f4f8ff;--muted:#8fa4bb;--line:rgba(160,190,220,.14);--green:#39d98a;--green2:#18b96b;--indigo:#42b7ff;--red:#ff5d7a;--amber:#ffc857;--shadow:0 10px 30px rgba(0,0,0,.22)}
html,body{background:#07111f!important;color:var(--text)!important}body{background:linear-gradient(180deg,#081522 0,#07111f 42%,#050d17 100%)!important}
.app{max-width:1080px;padding:18px 16px 112px}.top{margin-bottom:16px}.brand h1{font-size:22px}.brand small{font-size:11px}.logo{width:44px;height:44px;border-radius:13px;background:#1769aa;box-shadow:0 8px 22px rgba(23,105,170,.22)!important}.brand:hover .logo{transform:none;box-shadow:0 8px 22px rgba(23,105,170,.22)!important}
.actions{gap:6px}.iconbtn{background:#0d1b2a!important;border-color:var(--line)!important;box-shadow:none!important;backdrop-filter:none!important}.hero{grid-template-columns:1.2fr .8fr;gap:12px}.balance,.coach,.card,.timebar{background:#0d1b2a!important;border:1px solid var(--line)!important;border-radius:18px!important;box-shadow:0 8px 24px rgba(0,0,0,.18)!important;backdrop-filter:none!important}.balance,.coach{padding:20px}.balance:before,.coach:after{display:none}.amount{font-size:40px;margin:4px 0 15px}.flow{gap:8px}.flow div{background:#12263a;border-color:var(--line);box-shadow:none}.coach h3{font-size:19px}.coach p{color:#a8bad0}.timebar{margin-top:12px;padding:12px 14px}.monthnav button{background:#12263a;border-color:var(--line)}.grid{gap:12px;margin-top:12px}.card{padding:16px}.track,.goalbar{background:#172b40}.track i,.goalbar i{background:#42b7ff;box-shadow:none}.link{color:#58c2ff}.goal{background:#0f2031;border-color:var(--line);box-shadow:none}.tx:hover,.goal:hover{transform:none;background:inherit}.primary{background:#2388d6!important;border-color:#2388d6!important;box-shadow:0 7px 18px rgba(35,136,214,.2)!important}.secondary{background:#12263a!important;backdrop-filter:none!important}.fab{background:#2388d6!important;border:0;box-shadow:0 10px 24px rgba(35,136,214,.25)!important}.nav{background:#0a1827!important;border-color:var(--line)!important;box-shadow:0 8px 25px rgba(0,0,0,.3)!important;backdrop-filter:none!important}.nav button.active{background:#123b5c;color:#62c7ff;box-shadow:none}.modal{background:rgba(2,8,15,.82)!important;backdrop-filter:none!important}.sheet{background:#0d1b2a!important;border-color:var(--line)!important;box-shadow:0 -10px 40px rgba(0,0,0,.4)!important;backdrop-filter:none!important}.field input,.field select,.field textarea{background:#0a1725!important;border-color:var(--line)!important}.field input:focus,.field select:focus,.field textarea:focus{border-color:#42b7ff;box-shadow:0 0 0 3px rgba(66,183,255,.12)}
.sw-ai-overlay{position:fixed;inset:0;z-index:9999;display:flex;align-items:flex-end;justify-content:center;background:rgba(2,8,15,.72);padding:16px}.sw-ai-overlay:not(.show){display:none}.sw-ai-sheet{width:min(620px,100%);background:#0d1b2a;border:1px solid rgba(100,190,255,.2);border-radius:22px;padding:22px;box-shadow:0 18px 50px rgba(0,0,0,.4)}.sw-ai-kicker{font-size:10px;font-weight:900;letter-spacing:.12em;color:#58c2ff}.sw-ai-sheet h2{margin:5px 0 8px;font-size:25px}.sw-ai-copy{color:#b6c8da;line-height:1.5;margin:0 0 15px}.sw-ai-stats{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sw-ai-stats div{background:#12263a;border:1px solid var(--line);border-radius:13px;padding:12px}.sw-ai-stats span{display:block;color:#8fa4bb;font-size:10px}.sw-ai-stats strong{display:block;margin-top:3px;font-size:16px}.sw-ai-tip{margin:12px 0 16px;background:#0a1725;border-left:3px solid #42b7ff;border-radius:10px;padding:12px}.sw-ai-tip b{font-size:12px}.sw-ai-tip p{margin:4px 0 0;color:#a9bdd0;font-size:12px;line-height:1.45}
button{transition:transform .08s ease,background-color .12s ease,border-color .12s ease,color .12s ease!important}button:hover{box-shadow:none!important;filter:none!important}.logo,.logo::after,.logo::before{animation:none!important}.goal,.tx,.sw-page-layer,.sheet,.modal{will-change:auto!important}.sw-page-layer{backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
@media(max-width:700px){.app{padding:12px 12px 105px}.hero{grid-template-columns:1fr}.balance,.coach{padding:16px}.amount{font-size:32px}.grid{grid-template-columns:1fr}.timebar{border-radius:15px!important}.clockinfo{display:none}.fab{width:52px;height:52px;right:14px;bottom:78px}.nav{bottom:6px!important;width:calc(100% - 12px)!important;border-radius:15px!important}.nav button{min-height:40px;padding:5px 9px}.sw-ai-overlay{padding:0}.sw-ai-sheet{border-radius:22px 22px 0 0;padding:20px 16px 24px}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;document.head.appendChild(s)

 document.querySelectorAll('button,a').forEach(el=>{const text=(el.textContent||'').trim().toLowerCase();if(/\b(ai|insight|smart coach|coach)\b/.test(text)){el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();aiInsights()},{capture:true})}})
}
window.openPage=openPage;window.SaveWiseOpenPage=openPage;window.closePage=closePage;window.closeInsights=closeInsights;window.SaveWiseAI=aiInsights;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{bind();theme();clock();home()},{once:true});else{bind();theme();clock();home()}
let __swClockLast='';function clockTick(){const d=new Date(),key=d.toISOString().slice(0,16);if(key!==__swClockLast){__swClockLast=key;clock()}}document.addEventListener('visibilitychange',()=>{if(!document.hidden)clock()});clockTick();setInterval(clockTick,15000);
})();