(()=>{
'use strict';
const $=id=>document.getElementById(id),KEY='savewise_v1',AV=['🙂','😎','🤓','😄','🥳','🤩','😇','🤑','😌','🧑','👨','👩','🧔','👨‍💻','👩‍💻','🧑‍🎨','🦸','🧙','🐼','🐯','🦊','🐸','🐨','🐵'],CUR={INR:'₹',USD:'$',EUR:'€',GBP:'£'};
let db;try{db=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{db={}}if(!Array.isArray(db.profiles)||!db.profiles.length)db.profiles=[{id:1,name:'You',currency:'INR',balance:0,budget:0,transactions:[],goals:[],avatar:'🙂'}];if(!db.active)db.active=db.profiles[0].id;if(!db.theme)db.theme='dark';
const p=()=>db.profiles.find(x=>x.id===db.active)||db.profiles[0],save=()=>localStorage.setItem(KEY,JSON.stringify(db)),money=n=>(CUR[p().currency]||'₹')+Number(n||0).toLocaleString(),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),toast=s=>{let t=$('toast');if(t){t.textContent=s;t.classList.add('show');clearTimeout(window.__swT);window.__swT=setTimeout(()=>t.classList.remove('show'),2200)}};
function theme(){let dark=db.theme==='dark'||(db.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.classList.toggle('dark',dark);document.body.classList.toggle('light',!dark);if($('themeBtn'))$('themeBtn').textContent=dark?'🌙':'☀️';if($('swThemeBtn'))$('swThemeBtn').textContent=dark?'Switch to Light':'Switch to Dark'}
function closeInsights(){let x=$('insightsModal');if(x)x.classList.remove('show');let a=$('aiPanel');if(a)a.classList.remove('show')}
function openPage(id){document.querySelectorAll('.sw-page-layer').forEach(x=>{x.classList.remove('show');x.setAttribute('aria-hidden','true')});closeInsights();let x=$(id);if(!x)return;x.classList.add('show');x.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';if(id==='settingsPage')clock();if(id==='goalsPage')goals();if(id==='profilePage')profile()}
function closePage(id){let x=$(id);if(x)x.classList.remove('show');document.body.style.overflow=''}
function clock(){let d=new Date(),tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'Local';if($('clockLabel'))$('clockLabel').textContent=d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});if($('dateLabel'))$('dateLabel').textContent=d.toLocaleDateString([],{weekday:'long',day:'numeric',month:'short',year:'numeric'});if($('tzLabel'))$('tzLabel').textContent='🕐 '+tz;if($('swSettingsTimezone'))$('swSettingsTimezone').textContent='Automatically detected • '+tz}
function home(){let q=p(),now=new Date(),tx=(q.transactions||[]).filter(t=>{let d=new Date(t.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}),inc=tx.filter(t=>t.type==='income').reduce((a,t)=>a+Number(t.amount||0),0),exp=tx.filter(t=>t.type==='expense').reduce((a,t)=>a+Number(t.amount||0),0);if($('balance'))$('balance').textContent=money(q.balance);if($('income'))$('income').textContent='+ '+money(inc);if($('expense'))$('expense').textContent='− '+money(exp);if($('monthLabel'))$('monthLabel').textContent=now.toLocaleDateString(undefined,{month:'long',year:'numeric'});if($('monthMeta'))$('monthMeta').textContent=`${tx.length} transaction${tx.length===1?'':'s'} in this month`;theme()}
function goals(){let h=$('swGoalsContent');if(!h)return;let gs=Array.isArray(p().goals)?p().goals:[];h.innerHTML=gs.length?'<div class="sw-page-grid">'+gs.map(g=>{let pct=g.target?Math.min(100,g.saved/g.target*100):0;return `<div class="sw-goal-card"><h3>${g.icon||'🎯'} ${esc(g.name)}</h3><p>${money(g.saved)} of ${money(g.target)} • ${Math.round(pct)}%</p><div class="goalbar"><i style="width:${pct}%"></i></div><p>Goal date: ${g.date?new Date(g.date+'T00:00:00').toLocaleDateString():'Not set'}</p></div>`}).join('')+'</div><button class="btn primary" id="swPageAddGoal" style="margin-top:14px">＋ Add goal</button>':'<div class="sw-setting-card" style="text-align:center;padding:35px"><div style="font-size:34px">🐷</div><h3>No savings goals yet</h3><p>Create a goal for a trip, emergency fund, gadget or anything important to you.</p><button class="btn primary" id="swEmptyAddGoal">Create your first goal</button></div>';let a=$('swEmptyAddGoal')||$('swPageAddGoal');if(a)a.onclick=goalCreate}
function goalCreate(){openPage('goalCreatePage');let d=$('swGoalDate');if(d&&!d.value){let x=new Date();x.setMonth(x.getMonth()+1);d.value=x.toISOString().slice(0,10)}requestAnimationFrame(()=>$('swGoalName')?.focus())}
function goalSave(){let n=$('swGoalName')?.value.trim(),t=+$('swGoalTarget')?.value,s=+$('swGoalSaved')?.value||0,d=$('swGoalDate')?.value,i=$('swGoalIcon')?.value||'🎯';if(!n||t<=0||!d)return toast('Complete the goal details.');if(s<0||s>t)return toast('Already saved must be between 0 and target.');p().goals=p().goals||[];p().goals.push({id:Date.now(),name:n,target:t,saved:s,date:d,icon:i});save();closePage('goalCreatePage');openPage('goalsPage');toast('Savings goal created ✓')}
function profile(){let q=p(),a=q.avatar||'🙂';if($('swProfileName'))$('swProfileName').value=q.name||'You';if($('swProfileEmail'))$('swProfileEmail').value=q.email||'';if($('swProfileAbout'))$('swProfileAbout').value=q.about||'';if($('swProfilePreviewName'))$('swProfilePreviewName').textContent=q.name||'You';if($('swAvatarPreview'))$('swAvatarPreview').textContent=a;if($('headerAvatar'))$('headerAvatar').textContent=a;let g=$('swAvatarGrid');if(!g)return;g.innerHTML=AV.map(x=>`<button type="button" class="sw-avatar-choice ${x===a?'active':''}" data-avatar="${x}">${x}</button>`).join('');g.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{q.avatar=b.dataset.avatar;save();profile()})}
function legal(t){openPage('legalPage');if($('legalTitle'))$('legalTitle').textContent=t==='privacy'?'Privacy Notice':'Terms & Conditions';if($('legalContent'))$('legalContent').innerHTML=t==='privacy'?'<h3>Local data</h3><p>Core budgeting records stay in local browser storage in this prototype.</p><h3>Permissions</h3><p>Local time comes from your device/browser clock. Precise location is not required.</p>':'<h3>Intended use</h3><p>SaveWise is a personal budgeting and expense-tracking tool.</p><h3>Accuracy</h3><p>Check your own amounts, dates and decisions. Prototype features may change.</p>'}
function bind(){
$('settingsNav')?.addEventListener('click',()=>openPage('settingsPage'));$('goalsNav')?.addEventListener('click',()=>openPage('goalsPage'));$('headerAvatar')?.addEventListener('click',()=>openPage('profilePage'));
$('homeNav')?.addEventListener('click',()=>{document.querySelectorAll('.sw-page-layer.show').forEach(x=>x.classList.remove('show'));closeInsights();document.body.style.overflow=''});
$('swThemeBtn')?.addEventListener('click',()=>{db.theme=db.theme==='dark'?'light':db.theme==='light'?'system':'dark';save();theme()});$('themeBtn')?.addEventListener('click',()=>{db.theme=db.theme==='dark'?'light':'dark';save();theme()});
$('swNotifyBtn')?.addEventListener('click',()=>openPage('notificationsPage'));$('swBackupBtn')?.addEventListener('click',()=>openPage('backupPage'));$('swProfileBtn')?.addEventListener('click',()=>openPage('profilePage'));
$('swExportBackup')?.addEventListener('click',()=>{let u=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='savewise-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)});$('swImportBackup')?.addEventListener('change',e=>{let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!Array.isArray(d.profiles))throw 0;db=d;save();location.reload()}catch{toast('Invalid SaveWise backup.')}};r.readAsText(f)});
$('swResetBtn')?.addEventListener('click',()=>{if(confirm('Reset SaveWise data on this device? This cannot be undone.')){localStorage.removeItem(KEY);localStorage.removeItem('savewise_terms_privacy_accepted_v1');location.reload()}});
document.querySelectorAll('[data-open-legal]').forEach(b=>b.onclick=()=>legal(b.dataset.openLegal));document.querySelectorAll('[data-close-page]').forEach(b=>b.onclick=()=>closePage(b.dataset.closePage));
$('swAddGoalBtn')?.addEventListener('click',goalCreate);$('swGoalCreateBack')?.addEventListener('click',()=>{closePage('goalCreatePage');openPage('goalsPage')});$('swGoalCancel')?.addEventListener('click',()=>{closePage('goalCreatePage');openPage('goalsPage')});$('swGoalSave')?.addEventListener('click',goalSave);$('addGoal')?.addEventListener('click',()=>openPage('goalsPage'));
$('swSaveProfile')?.addEventListener('click',()=>{let q=p();q.name=$('swProfileName')?.value.trim()||'You';q.email=$('swProfileEmail')?.value.trim()||'';q.about=$('swProfileAbout')?.value.trim()||'';save();profile();home();toast('Profile saved ✓')});
$('swRequestNotifications')?.addEventListener('click',async()=>{if(!('Notification'in window))return toast('Notifications are not supported here.');let r=await Notification.requestPermission();if($('swNotificationStatus'))$('swNotificationStatus').textContent='Status: '+r;if(r==='granted')new Notification('SaveWise',{body:'Smart money reminders are enabled.'})});$('swTestNotification')?.addEventListener('click',()=>{if('Notification'in window&&Notification.permission==='granted')new Notification('SaveWise test',{body:'Notification test'});try{navigator.vibrate?.([20,30,40])}catch{}});
$('swReadPrivacy')?.addEventListener('click',()=>legal('privacy'));$('swReadTerms')?.addEventListener('click',()=>legal('terms'));$('swConsentCheck')?.addEventListener('change',e=>{if($('swAccept'))$('swAccept').disabled=!e.target.checked});$('swAccept')?.addEventListener('click',()=>{if($('swConsentCheck')?.checked){localStorage.setItem('savewise_terms_privacy_accepted_v1','yes');$('firstRunConsent')?.classList.remove('show')}});
const s=document.createElement('style');s.textContent=`
/* SaveWise performance layer: keep the premium look, remove mobile-unfriendly rendering costs. */
.nav,.iconbtn,.secondary,.modal,.sheet,.balance,.coach,.card,.timebar{backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
.balance,.coach,.card,.timebar{box-shadow:0 10px 28px rgba(0,0,0,.24)!important}
.nav{box-shadow:0 10px 28px rgba(0,0,0,.30)!important}
button{transition:transform .08s ease,background-color .12s ease,border-color .12s ease,color .12s ease!important}
button:hover{box-shadow:none!important;filter:none!important}
.logo{animation:none!important;filter:none!important}
.logo::after,.logo::before{animation:none!important}
.goal,.tx{transition:none!important}
.sw-page-layer{will-change:auto!important}
.modal.show{animation:none!important}.sheet{animation:none!important}
@media(max-width:600px){.app{padding-top:14px}.balance,.coach,.card{border-radius:17px}.balance,.coach{padding:17px}.card{padding:14px}.amount{font-size:34px}.fab{width:54px;height:54px;right:15px;bottom:82px}.nav{bottom:7px!important;width:calc(100% - 14px)!important;border-radius:16px!important}.nav button{min-height:42px;padding:6px 10px}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;document.head.appendChild(s)
}
window.openPage=openPage;window.SaveWiseOpenPage=openPage;window.closePage=closePage;window.closeInsights=closeInsights;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{bind();theme();clock();home()},{once:true});else{bind();theme();clock();home()}
let __swClockLast='';function clockTick(){const d=new Date(),key=d.toISOString().slice(0,16);if(key!==__swClockLast){__swClockLast=key;clock()}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)clock()});clockTick();setInterval(clockTick,15000);
})();
